version: "3.7"

services:
  
  hubmap-auth:
    # Avoid accidentally creating zombie processes
    init: true
    # Specifying a restart policy to avoid downtime
    restart: always
    # Map host machine port 80, 443, and 8443 to container ports
    ports:
      - "80:80"
      - "443:443"
      - "8443:8443" 
    volumes:
      # Mount the source code to container
      - "./hubmap-auth/src/:/usr/src/app/src"
      # Mount conf.d-test to the nginx conf.d on container
      - "./nginx/conf.d-test:/etc/nginx/conf.d"
      # Mount the static files
      - "/usr/local/src/hubmap/assets:/usr/src/assets"
      # Mount ssl certificates from host to container
      - "/etc/letsencrypt:/etc/letsencrypt"
      # Mount the API endpoints json file for API endpoints lookup
      - "./api_endpoints.test.json:/usr/src/app/api_endpoints.json"
      # Mount the secured_datasets json file for dataset files lookup
      - "./secured_datasets.json:/usr/src/app/secured_datasets.json"
