version: "3.7"

# Will use the hostname when talking between services on the same network
services:
  
  hubmap-auth:
    build: ./hubmap-auth
    # Build the image with name and tag
    image: hubmap-auth:0.1.0
    hostname: hubmap-auth
    container_name: hubmap-auth
    networks:
      - hubmap
    volumes:
      # Make the uwsgi logging generated on container available through from host
      - "./hubmap-auth/log:/usr/src/app/log"
      # favicon.ico
      - "./nginx/html:/usr/share/nginx/html"

  sample-api:
    build: ./sample-api
    # Build the image with name and tag
    image: sample-api:0.1.0
    hostname: sample-api
    container_name: sample-api
    networks:
      - hubmap
    volumes:
      # Make the uwsgi logging generated on container available through from host
      - "./sample-api/log:/usr/src/app/log"

networks:
  # This is creates the network named "gateway_hubmap" and we'll use this network name to enable communicaton between multiple docker-compose projects
  hubmap:
    driver: bridge
