version: "3.7"

services:
  
  hubmap-auth:
    environment:
      - DEPLOY_MODE=prod
    # Map host machine port 80, 443, and 8443 to container ports
    # Only root can listen on ports below 1024, we use higher-numbered ports
    # since nginx is running under non-root user hubmap
    ports:
      - "80:8080"
      - "443:4430"
      # 8443 is used by assets service on PSC VM
      - "8443:8443"
      # Proxy pass to ingest-api on PSC VM
      - "6666:6666"
    volumes:
      # Mount the app config to container in order to keep it outside of the image
      - "./hubmap-auth/src/instance:/usr/src/app/src/instance"
      # Mount conf.d-prod to the nginx conf.d on container
      - "./nginx/conf.d-prod:/etc/nginx/conf.d"
      # Mount ssl certificates from host to container
      - "/etc/letsencrypt:/etc/letsencrypt"
      # Mount the API endpoints json file for API endpoints lookup
      - "./api_endpoints.prod.json:/usr/src/app/api_endpoints.json"
