version: "3.7"

# Will use the hostname when talking between services on the same network
services:
  
  hubmap-auth:
    build: 
      context: ./hubmap-auth
      args:
        # The commons github branch to be used during image build (default to master if not set or null)
        - COMMONS_BRANCH=${COMMONS_BRANCH:-master}
    # Build the image with name and tag
    # Exit with an error message containing err if HUBMAP_AUTH_VERSION is unset or empty in the environment
    image: hubmap-auth:${HUBMAP_AUTH_VERSION:?err}
    hostname: hubmap-auth
    container_name: hubmap-auth
    # Avoid accidentally creating zombie processes
    init: true
    # Specifying a restart policy to avoid downtime
    restart: always
    environment:
      - HOST_GID=${HOST_GID:-1000}
      - HOST_UID=${HOST_UID:-1000}
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - gateway_hubmap
    volumes:
      # Mount the directory of requests_cache generated sqlite database
      - "./hubmap-auth/requests_cache:/usr/src/app/requests_cache"
      # Make the uwsgi/nginx log files generated on container available through from host
      - "./hubmap-auth/log:/usr/src/app/log"
      # favicon.ico and portal/ingest UI maintenance page
      - "./nginx/html:/usr/share/nginx/html"

networks:
  # This is the network created by gateway to enable communicaton between multiple docker-compose projects
  gateway_hubmap:
    external: true
