version: "3.7"
services:

  gateway:
    build: ./gateway
    hostname: gateway
    container_name: gateway
    networks:
      - hubmap


  nginx:
    build: ./nginx
    hostname: nginx
    container_name: nginx
    ports:
      - "5000:80"
    networks:
      - hubmap
    depends_on:
      - gateway

networks:
  hubmap:
