version: "3.7"

services:
  
  hubmap-auth:
    # Mapping ports in the HOST:CONTAINER format
    # Each API has its dedicated port and needs to be mapped here
    ports:
      # hubmap-auth
      - "8080:80" 
      # sample-api
      - "8181:81" 
      # uuid-api
      - "8282:82" 
      # entity-api
      - "8383:83" 
      # ingest-api
      - "8484:84" 
      # ingest-ui
      - "8585:85"
      # ingest-pipeline airflow
      - "8686:86"
    volumes:
      # Mount the source code to container
      - "./hubmap-auth/src/:/usr/src/app/src"
      # Mount conf.d-dev to the nginx conf.d on container
      - "./nginx/conf.d-dev:/etc/nginx/conf.d"
      # Mount the API endpoints json file for API endpoints lookup
      - "./api_endpoints.dev.json:/usr/src/app/api_endpoints.json"

  sample-api:
    volumes:
      # Mount the source code to container
      - "./sample-api/src/:/usr/src/app/src"

