version: "3.7"

services:
  
  hubmap-auth:
    environment:
      - DEPLOY_MODE=localhost
      - HOST_GID=${HOST_GID:-1000}
      - HOST_UID=${HOST_UID:-1000}
    # Mapping ports in the HOST:CONTAINER format
    # Each API has its dedicated port and needs to be mapped here
    # Only root can listen on ports below 1024, we use higher-numbered ports
    # since nginx is running under non-root user hubmap
    ports:
      # hubmap-auth
      - "8080:8080" 
      # assets
      - "8181:8181"
      # uuid-api
      - "8282:8282" 
      # entity-api
      - "8383:8383" 
      # ingest-api
      - "8484:8484" 
      # ingest-ui
      - "8585:8585" 
      # search-api
      - "8686:8686" 
    volumes:
      # Mount the source code to container
      - "./hubmap-auth/src/:/usr/src/app/src"
      # Mount conf.d-localhost to the nginx conf.d on container
      - "./nginx/conf.d-localhost:/etc/nginx/conf.d"
      # Mount the static files
      - "/hubmap-data:/hubmap-data"
      # Mount the API endpoints json file for API endpoints lookup
      - "./api_endpoints.localhost.json:/usr/src/app/api_endpoints.json"
