version: "3.7"

services:
  
  hubmap-auth:
    # Use the published image and tag from DockerHub
    image: hubmap/hubmap-auth:${HUBMAP_AUTH_VERSION:?err}
    environment:
      - DEPLOY_MODE=stage
    volumes:
      # Mount the app config to container in order to keep it outside of the image
      - "./hubmap-auth/src/instance:/usr/src/app/src/instance"
      # Mount conf.d-stage to the nginx conf.d on container
      - "./nginx/conf.d-stage:/etc/nginx/conf.d"
      # Mount ssl certificates from host to container
      - "/etc/letsencrypt:/etc/letsencrypt"
      # Mount the API endpoints json file for API endpoints lookup
      - "./api_endpoints.stage.json:/usr/src/app/api_endpoints.json"
