version: "3.7"

services:
  
  hubmap-auth:
    # Avoid accidentally creating zombie processes
    init: true
    # Specifying a restart policy to avoid downtime
    restart: always
    # Only map port 80 or 443
    ports:
      - "80:80"
      - "443:443" 
    volumes:
      # Mount the app config to container in order to keep it outside of the image
      - "./hubmap-auth/src/instance:/usr/src/app/src/instance"
      # Mount conf.d-test to the nginx conf.d on container
      - "./nginx/conf.d-test:/etc/nginx/conf.d"
      # Mount ssl certificates from host to container
      - "/etc/letsencrypt:/etc/letsencrypt"
      # Mount the API endpoints json file for API endpoints lookup
      - "./api_endpoints.test.json:/usr/src/app/api_endpoints.json"
