version: "3.7"

services:
  
  hubmap-auth:
    # Mapping ports in the HOST:CONTAINER format
    # Each API has its dedicated port and needs to be mapped here
    ports:
      # hubmap-auth
      - "8080:80" 
      # uuid-api
      - "8282:82" 
      # entity-api
      - "8383:83" 
      # ingest-api
      - "8484:84" 
      # ingest-ui
      - "8585:85" 
    volumes:
      # Mount the source code to container
      - "./hubmap-auth/src/:/usr/src/app/src"
      # Mount conf.d-localhost to the nginx conf.d on container
      - "./nginx/conf.d-localhost:/etc/nginx/conf.d"
      # Mount the API endpoints json file for API endpoints lookup
      - "./api_endpoints.localhost.json:/usr/src/app/api_endpoints.json"
