version: "3.7"

# Will use the hostname when talking between services on the same network
services:

  auth:
    build: ./auth/build
    hostname: auth
    container_name: auth
    networks:
      - hubmap
    volumes:
      # Mount source code onto the container when it is spun up
      # This way, as we make changes on the app source code, 
      # we won't have to keep building the image unless it is a major change, 
      # such as a software module dependency.
      - "./auth/src:/usr/src/app/src"
      # Make the logging generated on container available through from host
      - "./auth/log:/usr/src/app/log"

  nginx:
    build: ./nginx/build
    hostname: nginx
    container_name: nginx
    # Mapping ports in the HOST:CONTAINER format
    # Each API has its dedicated port and needs to be mapped here
    ports:
      # auth
      - "8080:80" 
      # sample-api
      - "8181:81" 
    networks:
      - hubmap
    volumes:
      # Make the logging generated on container available through from host
      - "./nginx/log:/usr/src/app/log"
    
  sample-api:
    build: ./sample-api/build
    hostname: sample-api
    container_name: sample-api
    networks:
      - hubmap
    volumes:
      # Mount source code onto the container when it is spun up
      # This way, as we make changes on the app source code, 
      # we won't have to keep building the image unless it is a major change, 
      # such as a software module dependency.
      - "./sample-api/src:/usr/src/app/src"
      # Make the logging generated on container available through from host
      - "./sample-api/log:/usr/src/app/log"

networks:
  hubmap:
