version: "3.7"

services:
  
  hubmap-auth:
    environment:
      - DEPLOY_MODE=dev
      - HOST_GID=1000
      - HOST_UID=1000
    # Map host machine port 80, 443, and 8443 to container ports
    # Only root can listen on ports below 1024, we use higher-numbered ports
    # since nginx is running under non-root user hubmap
    ports:
      - "80:8080"
      - "443:4430"
      # 8443 is used by ingest-api running on another machine
      - "8443:8443" 
    volumes:
      # Mount the source code to container
      - "./hubmap-auth/src/:/usr/src/app/src"
      # Mount conf.d-test to the nginx conf.d on container
      - "./nginx/conf.d-dev:/etc/nginx/conf.d"
      # Mount the static files
      - "/hubmap/assets:/usr/src/assets"
      # Mount ssl certificates from host to container
      - "/etc/letsencrypt:/etc/letsencrypt"
      # Mount the API endpoints json file for API endpoints lookup
      - "./api_endpoints.dev.json:/usr/src/app/api_endpoints.json"
      # Mount the secured_datasets json file for dataset files lookup
      - "./secured_datasets.json:/usr/src/app/secured_datasets.json"