version: "3.7"

services:
  
  hubmap-auth:
    # Avoid accidentally creating zombie processes
    init: true
    # Specifying a restart policy to avoid downtime
    restart: always
    environment:
      - DEPLOY_MODE=refactor
      - HOST_GID=${HOST_GID:-1000}
      - HOST_UID=${HOST_UID:-1000}
    # Map host machine port 80, 443, and 8443 to container ports
    # Only root can listen on ports below 1024, we use higher-numbered ports
    # since nginx is running under non-root user hubmap
    ports:
      - "80:8080"
      - "443:4430"
      # 8443 is used by ingest-api running on another machine
      - "8443:8443" 
    volumes:
      # Mount the VERSION file and BUILD file
      - "./VERSION:/usr/src/app/src/VERSION"
      - "./BUILD:/usr/src/app/src/BUILD"
      # Mount the source code to container
      - "./hubmap-auth/src/:/usr/src/app/src"
      # Mount conf.d-test to the nginx conf.d on container
      - "./nginx/conf.d-refactor:/etc/nginx/conf.d"
      # Mount ssl certificates from host to container
      - "/etc/letsencrypt:/etc/letsencrypt"
      # Airflow static files
      - "/home/airflow/.pyenv/versions/3.6.3/lib/python3.6/site-packages/airflow/www:/airflow-www"
      # Mount the API endpoints json file for API endpoints lookup
      - "./api_endpoints.refactor.json:/usr/src/app/api_endpoints.json"
      
